// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isttbkrbwgblltyroaoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdHRia3Jid2dibGx0eXJvYW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjEzMjMsImV4cCI6MjA3NDAzNzMyM30.pi5lqi37udIC2M6FfZ295wvEz9wS16-AhUp7AtJ-gnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});